# Form implementation generated from reading ui file 'color_scheduler.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Scheduler(object):
    def setupUi(self, Scheduler):
        Scheduler.setObjectName("Scheduler")
        Scheduler.resize(735, 309)
        Scheduler.setStyleSheet("QPushButton { \n"
"    background-color: rgb(35, 80, 135);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(70, 160, 255);\n"
"}\n"
"\n"
"QWidget#centralwidget {\n"
"    background-color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Scheduler)
        self.centralwidget.setObjectName("centralwidget")
        self.btnImpCS = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnImpCS.setGeometry(QtCore.QRect(50, 60, 75, 24))
        self.btnImpCS.setObjectName("btnImpCS")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 341, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lblColorSeq = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblColorSeq.setGeometry(QtCore.QRect(50, 100, 191, 16))
        self.lblColorSeq.setObjectName("lblColorSeq")
        self.lblTruck = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTruck.setGeometry(QtCore.QRect(50, 200, 191, 16))
        self.lblTruck.setObjectName("lblTruck")
        self.btnImpTC = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnImpTC.setGeometry(QtCore.QRect(50, 160, 75, 24))
        self.btnImpTC.setObjectName("btnImpTC")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 130, 341, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnSave = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(546, 270, 75, 24))
        self.btnSave.setObjectName("btnSave")
        self.btnReset = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(636, 270, 75, 24))
        self.btnReset.setObjectName("btnReset")
        self.tblOutput = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblOutput.setGeometry(QtCore.QRect(250, 30, 461, 231))
        self.tblOutput.setRowCount(4)
        self.tblOutput.setColumnCount(2)
        self.tblOutput.setObjectName("tblOutput")
        item = QtWidgets.QTableWidgetItem()
        self.tblOutput.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOutput.setHorizontalHeaderItem(1, item)
        self.btnVisualize = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnVisualize.setGeometry(QtCore.QRect(50, 230, 75, 24))
        self.btnVisualize.setObjectName("btnVisualize")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 275, 81, 20))
        self.label_2.setObjectName("label_2")
        self.lblAccuracy = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAccuracy.setGeometry(QtCore.QRect(140, 275, 51, 20))
        self.lblAccuracy.setText("")
        self.lblAccuracy.setObjectName("lblAccuracy")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 275, 71, 20))
        self.label_3.setObjectName("label_3")
        self.lblTotal = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTotal.setGeometry(QtCore.QRect(322, 275, 49, 20))
        self.lblTotal.setText("")
        self.lblTotal.setObjectName("lblTotal")
        self.lblQuantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblQuantity.setGeometry(QtCore.QRect(457, 275, 49, 20))
        self.lblQuantity.setText("")
        self.lblQuantity.setObjectName("lblQuantity")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 275, 51, 20))
        self.label_5.setObjectName("label_5")
        # Scheduler.setCentralWidget(self.centralwidget)

        self.retranslateUi(Scheduler)
        QtCore.QMetaObject.connectSlotsByName(Scheduler)

    def retranslateUi(self, Scheduler):
        _translate = QtCore.QCoreApplication.translate
        Scheduler.setWindowTitle(_translate("Scheduler", "Color Scheduler"))
        self.btnImpCS.setText(_translate("Scheduler", "Import"))
        self.label.setText(_translate("Scheduler", "Import Color Sequence:"))
        self.lblColorSeq.setText(_translate("Scheduler", "Imported file ..."))
        self.lblTruck.setText(_translate("Scheduler", "Imported file ..."))
        self.btnImpTC.setText(_translate("Scheduler", "Import"))
        self.label_4.setText(_translate("Scheduler", "Import truck closing csv:"))
        self.btnSave.setText(_translate("Scheduler", "Save"))
        self.btnReset.setText(_translate("Scheduler", "Reset"))
        self.tblOutput.setSortingEnabled(False)
        item = self.tblOutput.horizontalHeaderItem(0)
        item.setText(_translate("Scheduler", "Color"))
        item = self.tblOutput.horizontalHeaderItem(1)
        item.setText(_translate("Scheduler", "Quantity"))
        self.btnVisualize.setText(_translate("Scheduler", "Visualize"))
        self.label_2.setText(_translate("Scheduler", "Sort Accuracy:"))
        self.label_3.setText(_translate("Scheduler", "Total Entries:"))
        self.label_5.setText(_translate("Scheduler", "Total Qty:"))
